# Generated by Django 5.2.9 on 2025-12-15 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HexPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('q', models.IntegerField()),
                ('r', models.IntegerField()),
                ('s', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_type', models.CharField(max_length=16)),
                ('magnitude', models.IntegerField()),
                ('qangle', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='web.hexpoint')),
            ],
        ),
    ]
