# Generated by Django 5.2.9 on 2025-12-15 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_hexpoint_id_alter_shape_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='qangle',
        ),
        migrations.AlterField(
            model_name='shape',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_shapes', to='web.hexpoint'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='shape_type',
            field=models.CharField(choices=[('circle', 'Circle'), ('triangle', 'Triangle')], max_length=16),
        ),
        migrations.CreateModel(
            name='ShapePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.hexpoint')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.shape')),
            ],
            options={
                'ordering': ['idx'],
                'unique_together': {('shape', 'idx'), ('shape', 'point')},
            },
        ),
        migrations.AddField(
            model_name='shape',
            name='points',
            field=models.ManyToManyField(blank=True, related_name='member_shapes', through='web.ShapePoint', to='web.hexpoint'),
        ),
    ]
